site_name: Ktor-E-Commerce
site_description: Ktor-E-Commerce is a high performance backend solution for modern e-commerce applications, built with JetBrain's ktor.

theme:
  name: material
  icon:
    logo: material/library
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
   - navigation.tabs  # ðŸ‘ˆ enables top tab bar
  hide:
   - navigation

nav:
  - Home: index.md
  - API Reference:
      - Auth: auth.md
      - Profile: profile.md
      - Shop: shop.md
      - Shop Category: shop-category.md
      - Product: product.md
      - Product Category: product-category.md
      - Product Sub Category: product-sub-category.md
      - Brand: brand.md
      - Wishlist: wishlist.md
      - Shipping: shipping.md
      - Review Rating: review-rating.md
      - Cart: cart.md
      - Order: order.md
      - Payment: payment.md
      - Privacy Policy & Consents: privacy-policy.md
      - Inventory Management: inventory.md
  - Changelog: changelog.md

repo_url: https://github.com/piashcse/ktor-ecommerce
edit_uri: edit/main/docs/

extra_css:
  - css/extra.css
plugins:
  - search
  - meta  # ðŸ‘ˆ Required for per-page 'hide' to work