[versions]
ktor-version = "3.1.2"
kotlin-version = "2.1.20"
logback-version = "1.5.17"
exposed-version = "0.61.0"
flyway-version = "9.22.3"
postgresql-version = "42.7.4"
hikari-version = "6.2.1"
bcrypt-version = "0.10.2"
kotlinx-datetime-version = "0.6.2"
commons-email-version ="1.5"
valiktor-core-version = "0.12.0"
commons-io-version = "2.17.0"
ktor-swagger-ui-version = "5.0.2"
shadow-version = "8.3.6"
koin = "4.0.2"

[libraries]
ktor-server-core = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor-version" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json-jvm", version.ref = "ktor-version" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation-jvm", version.ref = "ktor-version" }
ktor-serialization-gson = { module = "io.ktor:ktor-serialization-gson-jvm", version.ref = "ktor-version" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common-jvm", version.ref = "ktor-version" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages-jvm", version.ref = "ktor-version" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth-jvm", version.ref = "ktor-version" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt-jvm", version.ref = "ktor-version" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor-version" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor-version" }
ktor-server-request-validation = { module = "io.ktor:ktor-server-request-validation", version.ref = "ktor-version" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor-version" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin-version" }

flyway-core = { module = "org.flywaydb:flyway-core", version.ref = "flyway-version" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed-version" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed-version" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed-version" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed-version" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed-version" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql-version" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari-version" }
bcrypt = { module = "at.favre.lib:bcrypt", version.ref = "bcrypt-version" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime-version" }
commons-email = { module = "org.apache.commons:commons-email", version.ref = "commons-email-version" }
valiktor-core = { module = "org.valiktor:valiktor-core", version.ref = "valiktor-core-version" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io-version" }
ktor-swagger-ui = { module = "io.github.smiley4:ktor-swagger-ui", version.ref = "ktor-swagger-ui-version" }
ktor-open-api = { module = "io.github.smiley4:ktor-openapi", version.ref = "ktor-swagger-ui-version" }
koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-logger = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor-version" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-version" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-version" }
